version: '3.8'

services:
  springboot-app:
    # Use the image name as 'myapp'
    image: docker-demo:latest  # You can name this as per your application, e.g., 'my-custom-app:latest'
    container_name: docker-demo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8068:8068"
    #environment:
      # Optionally set environment variables for your Spring Boot application
      # SPRING_PROFILES_ACTIVE: prod
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge
